### ISSUE TITLE
Enhancement: make it configurable when bs.setup() and bs.teardown() is called

### ISSUE THREAD

**Issue by uvexgmessow** [dsheiko/puppetry#10]
I'm writing tests for a website which you only can use when logged in. Unfortunately bs.teardown() is called after every test, so at the start of each test the login procedure has to be executed.
I changed the beforeEach and afterEach calls to beforeAll and afterAll and this lead to the desired behaviour to only have to login at the start of a test suite.

It would be great, if it could be configured where and when bs.setup() and bs.teardown() are called.

**Comment by dsheiko** [comment]
Oh thank you, a good point. I'm currently work on v1.1 and going to include this changes there

**Comment by dsheiko** [comment]
I implemented an alternative solution: https://github.com/dsheiko/puppetry/releases/tag/v2.0.0-RC.1
By using Snippets, you can once create login command/assertion sequence and refer to it in every test case like here:
https://docs.puppetry.app/snippets
