### ISSUE TITLE
Enhancement: Test Command Blocks

### ISSUE THREAD

**Issue by uvexgmessow** [dsheiko/puppetry#11]
Often it is necessary to execute the same commands in sequence and just the final commands differ between test cases.
It would be great if such command blocks could be managed in a separate tab and referenced in a test case. This way the test cases become cleaner and changes in the workflow of a website can be reflected in a single block without touching every related test case.

**Comment by dsheiko** [comment]
Do you mean some pane where one can define a sequence and then refer to it in the body of a test? I see the point, just need to think about implementation so to not make it overcomplicated. Interesting need to think about. For now just goes in the backlog

**Comment by dsheiko** [comment]
I guess from UI prospective it can be something like this
![sequnces](https://user-images.githubusercontent.com/1393963/51193798-fb0eab80-18e9-11e9-9d31-3f7373fdfd95.PNG)

What do you think?

**Comment by uvexgmessow** [comment]
Yes, that looks pretty much like I imagined it. One point though, commands can reference test targets, so I would rather see the "Sequences" tab next to "Test targets" and "Test groups".

Should it be possible one day to have multiple test suits open at once, then it would make sense to have common command sequences. On the other hand then it would make sense to have common test targets as well.

**Comment by dsheiko** [comment]
I'm not sure it belongs there https://github.com/dsheiko/puppetry/wiki/Domain-Model
I need to think on it more

**Comment by Aaron-Pool** [comment]
@dsheiko This is something the QA people at my work were really interested in as well (I'm a dev trying to help the QA group find no-dev-experience-needed QA tools). I think @dsheiko is correct that it should exist outside of a particular test suite, but it should have a "placeholder" functionality for interchangeable parts of a sequence that you can then drop in when you actually _use_ a sequence. Similar to the idea of a "code snippet" in IDEs.

**Comment by dsheiko** [comment]
I'm currently working on release 2.0.0 and this feature (code-name Snippets) is scheduled ether for the upcoming one or latest for 2.1, Snippets belong to the project and can be shared across suites

**Comment by dsheiko** [comment]
Available as Snippets in Alpha 2 https://github.com/dsheiko/puppetry/tree/release-2.0.0

**Comment by dsheiko** [comment]
Implemented in https://github.com/dsheiko/puppetry/releases/tag/v2.0.0-RC.1
documented https://docs.puppetry.app/snippets
