### ISSUE TITLE
Enhancement: Copy&Paste everything and everywhere

### ISSUE THREAD

**Issue by uvexgmessow** [dsheiko/puppetry#12]
At the moment copy&paste of commands / test cases and test groups is only possible by clicking "clone" and dragging the result around.
It would be great if the following features worked:

- Move a command to a different test case
- Copy&Paste one or more commands
- Copy&Paste one or more test cases
- Copy&Paste one more test groups
- Copy&Paste between test suites

**Comment by dsheiko** [comment]
Yeah, that's already in backlog https://github.com/dsheiko/puppetry/wiki/Backlog

**Comment by dsheiko** [comment]
Available in Alpha 2 https://github.com/dsheiko/puppetry/tree/release-2.0.0

**Comment by dsheiko** [comment]
Implemented in https://github.com/dsheiko/puppetry/releases/tag/v2.0.0-RC.1
documented https://docs.puppetry.app/managing-assets
