### ISSUE TITLE
running tests inside app breaks with TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by polyester** [dsheiko/puppetry#13]
Version: 1.0.5

Error is the same with Mac Zipfile, Linux AppImage, and using a git checkout on Linux.

The app starts, but any test that is started with F6 from the app will not run.

Error: 
`FAIL  ../.config/puppetry/.runtime-test/specs/react-html5-form-RWD.spec.js
  ● Test suite failed to run

    TypeError: Cannot read property 'prototype' of undefined

       6 |  * @returns {Promise<Undefined>}
       7 |  */
    >  8 | ElementHandle.prototype.select = async function( value ) {
         |               ^
       9 |   await this._page.evaluateHandle( ( el, value ) => {
      10 |       const event = new Event( "change", { bubbles: true });
      11 |       event.simulated = true;
`

Building from source according to https://github.com/dsheiko/puppetry/wiki/Dev-Notes has a problem as well, see below for npm error log

[2019-02-08T11_32_06_284Z-debug.log](https://github.com/dsheiko/puppetry/files/2845176/2019-02-08T11_32_06_284Z-debug.log)

Even when changing the order of the plugins in .babelrc to the recommended order with 

`//.babelrc
{
    "presets": ["@babel/preset-env"],
    "plugins": [
        ["@babel/plugin-proposal-decorators", { "legacy": true }],
        ["@babel/plugin-proposal-class-properties", { "loose": true }]
    ]
}`

 then the "npm run build" does complete, but then "npm start" does the same: the app opens, but any tests run from within the app fail with the same error.

in all cases (Linux AppImage, Mac Zip, build from source) tests that are **exported** as jest project run as intended.

**Comment by dsheiko** [comment]
Thank you very much.  I wasn't aware Puppeteer 1.12.x released where they moved `ElementHandle` from 
`puppeteer/lib/ExecutionContext` to `puppeteer/lib/JSHandle`. My bad - I didn't lock NPM properly to 1.11 branch. The fix is available at https://github.com/dsheiko/puppetry/releases/tag/v1.0.6
