### ISSUE TITLE
Is that possible to showing chromium?

### ISSUE THREAD

**Issue by bexoss** [dsheiko/puppetry#15]
Thanks for your application, Is there a way to showing browser? 
Like puppeteer, it has `headless: false` option. 
I saw your youtube guide video but I cannot find browser's working screen, 
so I just wonder - is it possible to show browser or not? 

Thanks.

**Comment by dsheiko** [comment]
After clicking run.. (or pressing F6) in the shown up modal window, simply tick on the switcher "Run in browser" 
https://pasteboard.co/I3PWubo.png
