### ISSUE TITLE
Snap package support [Feature Request]

### ISSUE THREAD

**Issue by mikeroyal** [dsheiko/puppetry#19]
I was wondering if you might have an interest in making [snap package](https://snapcraft.io/) version. Also, your app would be promoted on the [snap store page](https://snapcraft.io/store).

[Crafting your first snap](https://tutorials.ubuntu.com/tutorial/create-your-first-snap#0)

[Build and test snap](https://snapcraft.io/build)

[Getting Started snap template](https://github.com/snapcrafters/fork-and-rename-me)

**Comment by dsheiko** [comment]
I have indeed.  But till now I didn't manage to come up with a proper config. I have https://github.com/dsheiko/puppetry/blob/master/snap/snapcraft.yaml for ages, but it seems to have bugs, or just incorrect. I hope one day I put aside all other tasks and master this one :)

**Comment by mikeroyal** [comment]
I will take a look at it and see if I can fix the errors.

**Comment by dsheiko** [comment]
In fact I have a published snap "puppetry" since the very first release. I wanted to build it with Snapcraft CI, but seems one made with electron Builder is fine, so close the issue
