### ISSUE TITLE
[Feature] Changing screenshot directory

### ISSUE THREAD

**Issue by kkmuffme** [dsheiko/puppetry#20]
First off: amazing work. This is really, really helpful for beginners!

Would it be possible to change the screenshot directory? (either by defining any custom path, or by putting the screenshots in the projects directory)

**Comment by dsheiko** [comment]
Opps, I believed it does store in project directory. But you're right, it doesn't. On it.

**Comment by dsheiko** [comment]
I'm closing as it stores now the screenshots within the project
