### ISSUE TITLE
[Bug] Jest encountered an unexpected token

### ISSUE THREAD

**Issue by kkmuffme** [dsheiko/puppetry#21]
Tests run perfectly using the GUI, when I upload the exported folder, run npm install & then run npm test, npm test fails with this error:

```
> generated-test@1.0.0 test /my/directory
> cross-env NODE_ENV=test jest

 FAIL  specs/general-tests.spec.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /var/www/vhosts/staging/office/export/lib/helpers.js:16
      return { path, ...options };
                     ^^^
    SyntaxError: Unexpected token ...

      3 | const bs = require( "./BrowserSession" );
      4 |
    > 5 | const { makePng, png } = require( "./helpers" );
        |                          ^
      6 |
      7 | /**
      8 |  * Extending Puppeteer

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.require (lib/bootstrap.js:5:26)
      at Object.require (specs/general-tests.spec.js:6:28)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        3.035s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

Please let me know if you need any additional information

**Comment by dsheiko** [comment]
Hello. I suspect you have an outdated version of node.js (`node -v`). Destructuring (` { path, ...options }`) is supported somehow since ver 6.x (https://node.green/), but I never tested it with a version less than 10.x

**Comment by kkmuffme** [comment]
Thanks, yes, that was the problem. I was using v7.x, now with v11.x it works fine.

It seems the launcher args aren't working though?
`npm test PUPPETEER_LAUNCHER_ARGS="--no-sandbox"`

tells me "No tests found".
When I hardcode args: ['no-sandbox'] to the BrowserSession.js though, it finds the tests.

Then however I get:
>Cannot find target TABS_STEP (//*[@id="4"]/div/div[6]/ul/li[2]/a)

even though the XPath is directly copied from Chrome.

**Comment by dsheiko** [comment]
:) No please try as documented in README of exported package
```
npx cross-env PUPPETEER_RUN_IN_BROWSER=true PUPPETEER_LAUNCHER_ARGS="--start-maximized --ignore-certificate-errors" jest
```

**Comment by dsheiko** [comment]
And I'm closing the issue - resolved by adding warning code about Node.js version.
If you have other questions not related to this particular issue, please let's switch to https://gitter.im/dsheiko/puppetry - it's be more efficient there
