### ISSUE TITLE
[Feature] Screenshot comparison

### ISSUE THREAD

**Issue by kkmuffme** [dsheiko/puppetry#22]
I think it would be immensely helpful, if it could compare screenshots, using a tool like https://github.com/burnpiro/puppeteer-screenshot-tester but by setting the images to compare to in the GUI
(perhaps with a flag "skip image comparison", so the tests can be run without comparing, but just to generate the "before" screenshots)

There is also a more "advanced" resemble.js (https://github.com/rsmbl/Resemble.js), but I think the simplest form with just taking & comparing (areas of) screenshots, would be super helpful & help further automate things.

**Comment by dsheiko** [comment]
Thank for the idea. I have experience with Resemble.js, I know what you mean. Now gonna "sleep on it"

**Comment by dsheiko** [comment]
Puppetry 3.0.0 RC1 is available for download, implemented there, pls take a look
