### ISSUE TITLE
Can't install dependencies 

### ISSUE THREAD

**Issue by ceoaliongroo** [dsheiko/puppetry#24]
![image](https://user-images.githubusercontent.com/2622152/59676044-48f84a00-91cf-11e9-9dfe-c129dabba653.png)

I open puppeter with Administrator permisssion, but is not posible to install the dependencies.

this are the log:
```
[2019-06-18 13:16:25.795] [warn] Renderer process: RuntimeTest not ready, reason: could not lstat Error: ENOENT: no such file or directory, 

lstat 'C:\Users\carlosm\AppData\Roaming\puppetry\.runtime-test\node_modules\puppetry-lock.json'
[2019-06-18 13:16:25.827] [warn] Renderer process: removeRuntimeTestPath
[2019-06-18 13:19:51.212] [error] Main process: NPM(2): Error: EPERM: operation not permitted, rename 'C:\Users\carlosm\AppData\Roaming

\puppetry\.runtime-test\node_modules\babel-plugin-jest-hoist\package.json.1757312037' -> 'C:\Users\carlosm\AppData\Roaming\puppetry\.runtime-

test\node_modules\babel-plugin-jest-hoist\package.json'
[2019-06-18 13:19:51.217] [warn] Renderer process: removeRuntimeTestPath
```

also i tried install manually in the dependencies in the folder `.runtime-test` but everytime i close and open the application the folder is empty.

please help.

**Comment by dsheiko** [comment]
Puppetry creates `C:\Users\carlosm\AppData\Roaming\puppetry\.runtime-test` dynamically  and if it doesn't contain `node_modules` or  version specified in `C:\Users\carlosm\AppData\Roaming\puppetry\.runtime-test\node_modules\puppetry-lock.json` doesn't match the one of Puppetry than Puppetry tries to install the dependencies with NPM using it programatically. Actually if you managed to deliver dependencies with NPM in command line, you please create the `...\.runtime-test\node_modules\puppetry-lock.json`  file

```json
{
  "version": "1.0.10",
  "installed": "Thu Jun 13 2019 12:36:42 GMT+0200 (CEST)"
}
```
given your install version is 1.0.10

**Comment by dsheiko** [comment]
The problem with manually installed dependencies addressed in https://github.com/dsheiko/puppetry/releases/tag/v2.0.0-RC.1
No need for puppetry-lock.json now

**Comment by akeemphilbert** [comment]
I am having dependency issues where two packages are not being included recursive-readdir and shelljs. From your description of the problem here is it related to the fact that the .runtime-test folder is not being created? (I created a ticket for this here #38 )
