### ISSUE TITLE
Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"

### ISSUE THREAD

**Issue by ceoaliongroo** [dsheiko/puppetry#25]
Can't run the test suite:

![image](https://user-images.githubusercontent.com/2622152/60420953-81495080-9bf1-11e9-8902-96ac417676c8.png)

Error Details:
```
FAIL ../../../Roaming/puppetry/.runtime-test/specs/login.spec.js
Login
User login
× successfully (32ms)

● Login › User login › successfully

Chromium revision is not downloaded. Run "npm install" or "yarn install"

at Launcher.launch (node_modules/puppeteer/lib/Launcher.js:115:15)

● Login › User login › successfully

TypeError: Cannot read property 'goto' of undefined

37 | 
38 | // Navigating to "https://fwaservicestest/"
> 39 | await bs.page.goto( "https://fwaservicestest/", {"timeout":30000,"waitUntil":"load"} );
| ^
40 | 
41 | // @puppetry-command-id=3u8jxk3oys3:3u8jxk3p9k8:3u8jxk3u90o
42 | 

at Object.goto (specs/login.spec.js:39:21)

● Login › User login › successfully

TypeError: Cannot read property 'close' of undefined

42 | */
43 | async teardown() {
> 44 | this.browser.close();
| ^
45 | }
46 | }
47 | 

at BrowserSession.close [as teardown] (lib/BrowserSession.js:44:18)
at Object.teardown (specs/login.spec.js:28:14)

Test Suites: 1 failed, 1 total
Tests: 1 failed, 1 total
Snapshots: 0 total
Time: 1.041s
```

I install the dependencies (version 1.0.10) as you explain the the issue #24, so, i have to configure my chrome location? 

What is missing?
please help

**Comment by dsheiko** [comment]
It seems like when installing Google's Puppeteer post-install failed. Check with the NPM output. BTW, if you export the project for command-line (File/Export for CI...), npm install and npm test - doesn't work fine?

**Comment by ceoaliongroo** [comment]
I'll reinstall and everything pass without erorrs 
![image](https://user-images.githubusercontent.com/2622152/60491205-e9ab3700-9cb0-11e9-8e95-e2d5d6a4b785.png)


but still have the error: ```Chromium revision is not downloaded. Run "npm install" or "yarn install"```

any idea?

**Comment by dsheiko** [comment]
Seems like you simply were on a wrong directory. I had to install npm dependencies not in `C:\Users\carlosm\AppData\Roaming\puppetry\`, which Electron folder for the entire app, but in `C:\Users\carlosm\AppData\Roaming\puppetry\.runtime-test`

Please do the following:
1) Remove your polluted  `C:\Users\carlosm\AppData\Roaming\puppetry`
2) Launch Puppetry and press F6 (Run) (it will create again the folder)
3) If it still fails to install NPM dependencies programmatically, you go  
to `C:\Users\carlosm\AppData\Roaming\puppetry\.runtime-test`
4) `npm i > npm.txt`
5) in npm.txt must be something like
```
Chromium downloaded to C:\Users\carlosm\AppData\Roaming\puppetry\.runtime-test\node_modules\puppeteer\.local-chromium\win64-662092
```

And try it with the latest Puppetry 2.0 version, it doesn't require puppetry-lock.json file

**Comment by ceoaliongroo** [comment]
there is no a folder ```.local-chromium\win64-662092``` . under the folder ```puppeteer``` 

how i can install the chromium manually?

**Comment by dsheiko** [comment]
When you install dependencies and it comes to Puppeteer, the package runs `node install.js`, which normally downloads Chromium in something like
```
c:\Users\carlosm\AppData\Roaming\puppetry\.runtime-test\node_modules\puppeteer\.local-chromium\win64-662092\chrome-win 
```

Manually Chromium can be downloaded from
- https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html
- https://download-chromium.appspot.com/

Here folks are discussing the very same issue with Chromium - https://github.com/GoogleChrome/puppeteer/issues/1425

And you must be right about `PUPPETEER_EXECUTABLE_PATH`. That looks like the way to set the path without touching the code. Puppetry [doesn't override this property](https://github.com/dsheiko/puppetry/blob/master/jest-pkg/lib/BrowserSession.js)

**Comment by ceoaliongroo** [comment]
I'm behind a proxy and is not possible download the chromium with the npm command.

i'll tray manually and configure with ```PUPPETEER_EXECUTABLE_PATH```

**Comment by dsheiko** [comment]
I believe it's obsolete now
