### ISSUE TITLE
Protect template variable as password

### ISSUE THREAD

**Issue by ceoaliongroo** [dsheiko/puppetry#28]
Add option to chose visual protected  ```Template Variable``` as password.  show in value ```****```

**Comment by dsheiko** [comment]
OK, accepted https://github.com/dsheiko/puppetry/projects/3

**Comment by dsheiko** [comment]
Well, what I did - is hidden variables
![hidden-vars](https://user-images.githubusercontent.com/1393963/61460981-1ed1ad80-a970-11e9-9496-b1da9010dcac.gif)

They seem hidden from user perspective, but still available in project files. It doesn't make sense to encrypt, as after exporting the test project is delivered as open code. Meaning, anyone can figure out how to decrypt it the same way the system does it. Thus, I assume, the only secure way to keep sensitive data (credentials) is via [env variables](https://en.wikipedia.org/wiki/Environment_variable), what can be achieved with [template expressions](https://docs.puppetry.app/template#environment-variables)

The feature will go live with 2.1.0 https://github.com/dsheiko/puppetry/tree/release-2.1.0
