### ISSUE TITLE
Problem with the recorder

### ISSUE THREAD

**Issue by jeffburton** [dsheiko/puppetry#29]
My app breaks in the recorder (never properly loads), but I can't figure out why because I can't see the console. Is there any way to get access to the chrome console while recording?

**Comment by dsheiko** [comment]
Thanks for reporting. I will think of including a button to show DevTools. But now you can

```
git clone https://github.com/dsheiko/puppetry.git
cd puppetry
npm i
npm start
```
just uncomment webview.openDevTools() in
https://github.com/dsheiko/puppetry/blob/master/app/recorder/renderer.js#L159

**Comment by dsheiko** [comment]
Added the button to open Devtools
https://github.com/dsheiko/puppetry/releases/tag/v2.0.2
