### ISSUE TITLE
Error starting the demo project

### ISSUE THREAD

**Issue by iX315** [dsheiko/puppetry#3]
This error will be thrown starting the demo project by simply pressing the keyboard shortcut F6 (as suggested)
![screen shot 2018-11-23 at 22 33 37](https://user-images.githubusercontent.com/8116734/48960781-e6f4a080-ef6f-11e8-8a7b-f9a92c139109.png)

instead should appear the dependencies install modal first
![screen shot 2018-11-23 at 22 35 17](https://user-images.githubusercontent.com/8116734/48960813-1efbe380-ef70-11e8-818f-b4c0257bcaac.png)

**Comment by dsheiko** [comment]
Thank you! The fix is pushed to Github, https://github.com/dsheiko/puppetry/commit/b4e41ec5b80b0cb67db5554f3309274484d6d57e
I'm going to release 1.0.1 on Monday
