### ISSUE TITLE
Constantly getting Navigation Timeout Error

### ISSUE THREAD

**Issue by monika-12** [dsheiko/puppetry#34]
**Steps:**
1. Created a simple WordPress admin login test case.
2. When Running the test case getting failure error - "Navigation Timeout Exceeded: 3000ms exceeded"

How can I fix this error please let me know.

**Screenshot:**
https://cl.ly/6f4b6c21650f

**Comment by dsheiko** [comment]
It means that a test command (most likely page.waitForSelector or page.waitForNavigation) was waiting for an action which never happened. It would help me a lot to find the issue if you could share your project. Besides take a look at "Error details" panel you need to click on it to expand the details)

**Comment by monika-12** [comment]
Here is the screenshot of the error details - https://cl.ly/531ca49836df

Project File - https://cl.ly/16e63b57381f

Let me know if you need any help to debug the issue.

**Comment by dsheiko** [comment]
https://cl.ly/16e63b57381f it's wrong :). I mean the Puppetry project with the tests. Please use "Project save as..." https://docs.puppetry.app/project#save-project-as menu item to save the project into a separate folder, compress it and share with me.

**Comment by monika-12** [comment]
@dsheiko Sorry for missing it.
Here Is the Compress folder of the project - https://cl.ly/4ea85a379abe
Let me know if I miss something.

**Comment by monika-12** [comment]
Here is the another Project file getting new error `Duplicate declaration "A_CLASS_AB_ITEM"`
File - https://cl.ly/1999d95663d0

**Comment by monika-12** [comment]
@dsheiko Did you get a chance to look into the above-mentioned issue?

**Comment by dsheiko** [comment]
Here the fix for the first project
https://sharefiles.app/download/764b7c4da7edd43462a760c2ce8a953fdfc65ae2
You create tests manually - everything goes fine, the Recorder seems raw yet. I need to work on it.

Here the fixed test

```
WP Test
environment: test
template variables:

WP Test
   filename: wp--test.json
   timeout: 50000
   
   targets:
      INPUT_ID_USER_LOGIN = #user_login
      INPUT_ID_USER_PASS = #user_pass
      BUTTON_LOGIN = #wp-submit

   describe: Recorded session

      test: Recorded test case
         page.goto(`https://s1.demo.opensourcecms.com/wordpress/wp-login.php`)
         INPUT_ID_USER_LOGIN.type(`opensourcecms`)
         INPUT_ID_USER_PASS.type(`opensourcecms`)
         BUTTON_LOGIN.click(left button)
         page.waitForNavigation(`domcontentloaded`)
         page.screenshot(`Page after login`)
```

**Comment by dsheiko** [comment]
As for the second... It really looks like an issue, weird one - never met such before. Thanks. I going to take care

**Comment by monika-12** [comment]
Thank you for providing the fixes. 
If you are using slack for Discussion/FAQ then can you please share the slack invite link?

**Comment by dsheiko** [comment]
Sure, it's https://puppetry-app.slack.com/

**Comment by monika-12** [comment]
Yes, I checked this link but I can't sign in there without any invitation link. Can you please send me a slack invitation link on this email ID - `monikar@bsf.io`

**Comment by dsheiko** [comment]
Sent out

**Comment by monika-12** [comment]
Got it. Thanks...

**Comment by dsheiko** [comment]
The recorder fixed https://github.com/dsheiko/puppetry/releases/tag/v2.0.3
It didn't capture click event on input[type=submit], that's why you got timeout

**Comment by monika-12** [comment]
@dsheiko Thanks for the quick update.
