### ISSUE TITLE
CodeceptJS support

### ISSUE THREAD

**Issue by DavertMik** [dsheiko/puppetry#39]
Hi, I'm maintainer of CodeceptJS https://codecept.io testing framework.
We also use Puppeteer for testing, that's how I found this project.

CodeceptJS is better designed for a problem you are solving with Puppettry. 
The code is already user-friendly, focuses on test actions, and hides Puppeteer API calls under elegant DSL. So tests can be written with minimal JavaScript knowledge.

Maybe puppetry could be more effective and more user-friendly, if instead of calling puppeteer api directly it could generate codeceptjs code. Just an idea!

**Comment by dsheiko** [comment]
Looks like not an issue, but self-promotion to me. On this behalf I'm closing and deleting this
