### ISSUE TITLE
All projects gets deleted on deletion of a single project from listing.

### ISSUE THREAD

**Issue by jadhavravindra** [dsheiko/puppetry#40]
When user tried to delete any project then other indepedent project also gets deleted  but when again tried to create new project then found that, the deleted project also gets back in listing.

Issue Video Link:  https://www.screencast.com/t/tI1GFdB0N

**Comment by dsheiko** [comment]
Oh... Thanks, I'm on it

**Comment by jadhavravindra** [comment]
yes you right, found the root cause of this issue here as well, 
**Actual Issue:** Project name folder is not created in the project location directory. and due to this all suits added in same directory hence that created problem while delete the project.
**Solution :** When user create new project with project title then project name folder should be auto create inside the project location.
**Video link:** https://share.getcloudapp.com/z8uqe2b4  


![image](https://user-images.githubusercontent.com/31184005/65220006-7064f880-dad7-11e9-9fe6-6455cf0574a4.png)

**Comment by dsheiko** [comment]
I'm not yet sure if it would be intuitively understandable login. When you select a folder I expect it'll be project location. On the other hand, we definitely have an issue. For example some people select Desktop and likely expecting the behaviour as you described. I need to think on it more. Just for the consistency - creating project and then opening, shall be about the same folder...

**Comment by dsheiko** [comment]
Puppetry 3.0.0 RC1 is available for download, implemented there, pls take a look
