### ISSUE TITLE
add command/assertion button not working properly after creating multiple test cases and snippets

### ISSUE THREAD

**Issue by jadhavravindra** [dsheiko/puppetry#42]
getting same **Edit Reference** snippets window, after click on add command button,
**Please Note:** facing this issue after creating multiple test cases with commands and snippets in a group.

**Snapshot link:** https://www.screencast.com/t/JvMAjXmYGs

**Comment by dsheiko** [comment]
Oh thank you, very much appreciated. I'm going to fix it ASAP

**Comment by dsheiko** [comment]
Puppetry 3.0.0 RC1 is available for download, I cannot reproduce the issue on that branch
