### ISSUE TITLE
Please add Publisher 

### ISSUE THREAD

**Issue by rsc2015** [dsheiko/puppetry#44]
_Publisher: | Unknown publisher_

Windows keeps warning before running Puppetry. Adding a publisher will be nice to download the app without risk.

**Comment by dsheiko** [comment]
Yeah, I was considering buying certificates for Windows (https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate) and Mac, but it costs money . The project is not meant to make any money, so actually I don't have any budget, at least for now
