### ISSUE TITLE
How to test pages with Shadow DOM ?

### ISSUE THREAD

**Issue by IntranetFactory** [dsheiko/puppetry#45]
I've seen that "querying in Shadow DOM" should now be possible with 3.0 RC. I tried to record a session with a login form using Shadow DOM, but it either doesn't work or I did not figure out to use it.

I also tried to enter the JS Path to the <input> as a selector, but it seems to only accept CSS selectors or XPath.

So I'm trying to recreate a simple puppeteer script https://gist.github.com/IntranetFactory/59c796b1a6b7870b7840c20e8ae426b1 with Puppetry

Should it be possible to test forms using Shadow DOM in 3.0 RC ?

**Comment by dsheiko** [comment]
Sorry, documentation for 3.0 is in progress. You have to use Options while creating a local target to bind it with a ShadowHost container. Just check the demo project distributed with the app.
1) Close all tabs
2) Click on Demo project button
3) Open shadow-dom.json suite
4) Check the targets
5) Run the tests

![screenshot-1573549023](https://user-images.githubusercontent.com/1393963/68657196-87522500-0533-11ea-8524-72b93bde7234.png)
![screenshot-1573549048](https://user-images.githubusercontent.com/1393963/68657213-9042f680-0533-11ea-9a83-1e3771da88c2.png)
![screenshot-1573549063](https://user-images.githubusercontent.com/1393963/68657224-95a04100-0533-11ea-94c8-b53f40970c51.png)
![screenshot-1573549101](https://user-images.githubusercontent.com/1393963/68657238-9b962200-0533-11ea-91c4-b58f2609a81c.png)

**Comment by IntranetFactory** [comment]
That looks great. I was really surprised to see that Shadow Dom is already supported.   

Are nested shadow roots possible as well? A sample JS path is e.g.
`document.querySelector("#board").shadowRoot.querySelector("#container > at-card-board").shadowRoot.querySelector("#workplace-layout").shadowRoot.querySelector("#cardf356eead-af8d-4a2b-a9a0-4b59542b2461 > at-app-card").shadowRoot.querySelector("#container").shadowRoot.querySelector("#footer8").shadowRoot.querySelector("#container > at-link > div > at-carbon-clamp")`

**Comment by dsheiko** [comment]
Sure, you can chain selectors, but for Shadow DOM all the targets must have CSS (not Xpath) selectors

**Comment by IntranetFactory** [comment]
So I cannot just paste the JS path from the chrome developer tools (like the one pasted above)? Do you have any plans to detect the JS path in recording mode?

**Comment by dsheiko** [comment]
1) You can go with https://docs.puppetry.app/test-step/commands#page-evaluate
2) You can go with https://docs.puppetry.app/test-step/commands#page-runjs (be aware of Puppeteer API extension https://docs.puppetry.app/command-api)

![screenshot-1573577410](https://user-images.githubusercontent.com/1393963/68692015-06b41880-0575-11ea-892a-0bf4c61ae6ec.png)
![screenshot-1573577422](https://user-images.githubusercontent.com/1393963/68692021-087ddc00-0575-11ea-98e6-b79f3f9fcf5e.png)

Actually, it would be more convenient to continue with HOW-TO on Slack http://puppetry.dsheiko.com/ or at least on Facebook page https://www.facebook.com/pg/puppetry.testing/

**Comment by dsheiko** [comment]
RC2 is released, where I provided test cases for chained methods
You can download the test project from https://github.com/dsheiko/puppetry/tree/release-3.0.0/project-test
On that I think we can close this issue
