### ISSUE TITLE
ver 3.0.0-RC3 fails simple login/logout test

### ISSUE THREAD

**Issue by mpowered-mweigel** [dsheiko/puppetry#46]
I was really excited to see the possibility of this tool being able to automate my E2E testing. However, maybe it does not work with the framework I am using - ext js by Sencha? You can see the results for yourself by loading http://www.ticavio.com/ticavio/cloud/tc_10000/index.html and log in with guest@ticavio.com pwd guest543 and then clicking the logout link in the left menu. My results:

Error: Evaluation failed: DOMException: Failed to execute 'querySelector' on 'Document': '/html[1]/body[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/table[3]/tbody[1]/tr[1]/td[1]/div[1]/span[1]' is not a valid selector.

**Comment by dsheiko** [comment]
Oh thank you very much. A good one. I really missed that case. Recorder automatically now provides steps with "wait for the target" (recently introduced one), which I tested only for CSS selectors. The condition for xPath was wrong. Just fixed it. It will be deployed in a few days
