### ISSUE TITLE
Incorrect selectors for querySelectorAll

### ISSUE THREAD

**Issue by nin-jin** [dsheiko/puppetry#48]
> Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': '#$mol_app_todomvc.Root(0).Title()' is not a valid selector.

App: https://mol.js.org/app/todomvc/

You should use `getElementById`:

```
document.getElementById('$mol_app_todomvc.Root(0).Task_row(1).Title()')
```

Or use right escaping:

```
document.querySelector('#\\$mol_app_todomvc\\.Root\\(0\\)\\.Task_row\\(1\\)\\.Title\\(\\)')
```

**Comment by dsheiko** [comment]
Thanks, a nice one. It gets included in v3.0.1

**Comment by nin-jin** [comment]
When will it be?

**Comment by dsheiko** [comment]
I believe in a week, want to collect other possible issues for the release

**Comment by nin-jin** [comment]
I really want to try puppetry.

**Comment by dsheiko** [comment]
But as I understand, you built Puppetry when testing the fix. So you can run it like "npm start". I need extra checks before releasing the last changes.
You can also build it on your own with:
npm run dist:all
it creates dist folder with builds per platform

**Comment by nin-jin** [comment]
> But as I understand, you built Puppetry when testing the fix. 

Nope. :-)

**Comment by dsheiko** [comment]
You can play with dev version https://we.tl/t-jyrOwDnXGu

**Comment by nin-jin** [comment]
Yeah, it works. But could you make custom names for selectors are optional? It completely useless for me, because ids is already readable.

![image](https://user-images.githubusercontent.com/442988/70260329-17853200-17a1-11ea-9952-00567281f3d4.png)

**Comment by dsheiko** [comment]
Oops,  didn't get it. Recorder tries to suggest a passing name automatically. Optionally you can right-click on a target and specify a custom name.

**Comment by nin-jin** [comment]
I don't want to name selectors (so for assertion I have no choice), I want to use selector itself (but without escaping of course).

**Comment by dsheiko** [comment]
In your particular case it's so, but usually the selectors are like "div > div:nth-child(2) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)". Too long for searching in select and meaningless. You can rename targets as you wish. When editing as CSV (as a text) you can use any tools for bulk renaming.

**Comment by nin-jin** [comment]
"div > div:nth-child(2) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2)" is too fragile selectors.

I don't want to name or rename selectors. I want selectors naming to be optional.
