### ISSUE TITLE
setAttribute with false won't remove disabled attribute

### ISSUE THREAD

**Issue by mortocks** [dsheiko/puppetry#5]
**Setup**
Element selector `input[name="update_cart"]` (works in browser)
Set attribute `disabled` to `false` (as per tool tip) https://www.dropbox.com/s/u7alqx1s7we9vf6/attribute.png?dl=0 

**Result**
Input is still disabled. 

**Debugging Steps**

Running in chrome browser console
`document.querySelector("input[name='update_cart']").setAttribute('disabled', false);`
does nothing

running
`document.querySelector("input[name='update_cart']").removeAttribute('disabled');`
works

**Comment by dsheiko** [comment]
A good one, I've forgotten  to stringify parameter value. Fixed now with v1.0.2
