### ISSUE TITLE
Application can't be opened

### ISSUE THREAD

**Issue by eduardsv** [dsheiko/puppetry#50]
I can't open the application. Not sure why it happens, it doesn't give me any specific errors.
Here's what I see:
<img width="595" alt="About_This_Mac" src="https://user-images.githubusercontent.com/7442464/69871936-feb1e380-12ab-11ea-9fdc-a4d0f0d98831.png">

If you need any other information, I'll be glad to help.

**Comment by dsheiko** [comment]
I've just checked on macOS Mojave v.10.14.6, runs smoothly. I still think, that can be related to the fact the app is unsigned. After brief googling I found https://www.fireebok.com/resource/how-to-fix-that-app-can-not-open-on-macos-catalina.html
Please try to follow these steps, and let me know if it gives you "Open" button

**Comment by eeliane** [comment]
Hello. macOS Catalina v. 10.15.1. 
Puppetry 3.0.0: App can't be opened, that instruction didn't help. 
Puppetry 3.0.0 RC3: can be opened successfully

**Comment by lozik4** [comment]
> Hello. macOS Catalina v. 10.15.1.
> Puppetry 3.0.0: App can't be opened, that instruction didn't help.
> Puppetry 3.0.0 RC3: can be opened successfully

I have exactly the same problem.

**Comment by dsheiko** [comment]
It seems like like something related to macOS Catalina. At home I have macOS High Sierra v.10.13.6 and do not experience any issues with Puppetry 3.0.0. At  the moment I am short of ideas. Gonna research

**Comment by dsheiko** [comment]
@lozik4 Can you please try this build https://github.com/dsheiko/puppetry/releases/download/v3.0.0/puppetry-mac-v3.0.0-repacked.zip
I repacked it with the latest electron-builder directly on the Mac

**Comment by elnirael** [comment]
hi @dsheiko 
used repacked build and the problem remains the same
"Application can't be opened"

**Comment by dsheiko** [comment]
Thanks for quick reply. We've just managed to open Puppetry on a college's  MacbookPro with Catalina by following the instructions: 
https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac
If short, locate it in Finder and Control-click, then "open" menu item.

**Comment by msiviero** [comment]
Same problem here, with Catalina 10.15.1 (19B88). The ctrl+click procedure does not help.

**Comment by eeliane** [comment]
It didn't help me either (the same version of Catalina)

**Comment by dsheiko** [comment]
Here one of users reported that it works if you move the app out from the Downloads folder, e.g to Desktop

**Comment by eeliane** [comment]
It didn't help, this app still can't be opened.

**Comment by msiviero** [comment]
Same for me. If it's of any help, opening the app via "open" command in terminal gives me:
LSOpenURLsWithRole() failed with error -10810 for the file /Users/marco.siviero/Desktop/puppetry.app.

**Comment by msiviero** [comment]
Problem "almost" solved. If you give the directory execution permission:
`chmod -R +x puppetry.app`
Then the app opens (you still need to manually authorise it, though). 
@dsheiko maybe is something you can change your pipeline to ensure this

**Comment by msiviero** [comment]
Almost solved, as it keeps crashing. If is of any help, I attach the crash report
[crash_details.txt](https://github.com/dsheiko/puppetry/files/3939922/crash_details.txt)

**Comment by dsheiko** [comment]
Unfortunately my just few years old MacbookPro refuses Catalina, so I cannot test self. It seems like electron-builder does not fully support Catalina. I tried a workaround, can anybody check if it opens on Catalina https://github.com/dsheiko/puppetry/releases/download/v3.0.0/puppetry-mac-v3.1.0.zip ?

**Comment by dsheiko** [comment]
@msiviero  thanks, studying the crash log

**Comment by msiviero** [comment]
No problem, I'm happy to do something to help, if I can. By the way, v3.1.0 doesn't work too (same errors).If you provide me the steps to build the project maybe I can try to do some quick checks on my machine (I have a little electron and electron builder knowledge)

**Comment by dsheiko** [comment]
It's simple. You just need NPM. 
1) Download (or git clone) the project
2) Enter the project directory
3) run `npm install`
4) run `npm run dist:m`
5) You'll find the build in `dist` folder

Notes:
- The application is based on Electron.js v7.0.1
- The packager is https://github.com/electron-userland/electron-builder
- Packager settings can be found in `package.json` property `build`
- You can run the app without packaging with `npm start`
- The version 3.1.0 is available in the branch dev (`git checkout dev`)

**Comment by dsheiko** [comment]
@msiviero I'm trying to build DMG by the template https://github.com/Automattic/simplenote-electron/blob/develop/electron-builder.json - cannot do it on vitual machine. 
Can you try to build from `dev` branch (`git checkout dev && git pull origin dev`)? 
```
npm i && npm run build && npm run dist:m
```

**Comment by msiviero** [comment]
Hi @dsheiko. I've tried the build from my macbook pro and the dist (not packaged) opens just fine.
I'm trying with _dev_ branch as soon as I can

<img width="1680" alt="Screenshot 2019-12-12 at 15 41 04" src="https://user-images.githubusercontent.com/4665700/70728562-eefdba80-1d01-11ea-9b2d-64853bdacd6f.png">

**Comment by dsheiko** [comment]
Well, I changed packaging strategy. Now there 2 options zip and DMG. The last one works fantastic on High Sierra
Can anybody check both builds on Catalina please?
https://github.com/dsheiko/puppetry/releases/download/v3.0.0/puppetry-mac-3.1.0.dmg
https://github.com/dsheiko/puppetry/releases/download/v3.0.0/puppetry-mac-3.1.0.zip

**Comment by msiviero** [comment]
Hi, the .zip doesn't work, while the .dmg opens correctly on Catalina 10.15.1 (19B88)

**Comment by dsheiko** [comment]
Thanks, then I go on with it

**Comment by dsheiko** [comment]
Latest DMG is available in https://github.com/dsheiko/puppetry/releases/tag/v3.1.0

**Comment by dsheiko** [comment]
On Mac can be installed with [Homebrew](https://brew.sh/):
```
brew cask install puppetry
```
