### ISSUE TITLE
Snippet cannot be used 2 times with different data

### ISSUE THREAD

**Issue by maxcc0** [dsheiko/puppetry#52]
I have a snippet, lets say "Find Customer" which picks up {{ CUSTOMER_ID }} from the template and finds customer. CUSTOMER_ID is set in the template vars. 

**What works okay**
When this snippet is used one time, it works okay.
Case: user finds customer 
 ---(1) "Find Customer"

**What does not work okay**
When the snippet is used 2 times
Case: user finds customer (bad customer is also detected)
 ---(1) "Find Customer"
 ---(2)  "Find Customer" with CUSTOMER_ID=xxx

Here, I expect 1. to run with default value and 2. to run with xxx. However both steps run with xxx.

**Comment by dsheiko** [comment]
It works like that. Right before the snippet gets executed the variables assigned
```javascript
Object.assign( ENV, {"FIRST_NAME":"Latin script"} );
```
And snippet references this variable e.g. like
```javascript
await ( await bs.getTarget( "FIRSTNAME_INPUT" ) ).type( `${ ENV[ "FIRST_NAME" ] }` );
```
You can check `exhaustive-testing.json` suite in demo project (https://github.com/dsheiko/puppetry/tree/master/project-demo)

When you run the snippet second time with new value, the variable is overriden:
```javascript
Object.assign( ENV, {"FIRST_NAME":"αßÁáÀàÅåÄäæ"} );
``` 
But you probably have the variable set in Project / Template Variables and as soon as you set a new value in Snippet reference it has the new value (overridden)

**Comment by maxcc0** [comment]
Would you consider making it like the way I've described above? If an override is given, then apply the override otherwise use the variable value from Templated variables? This way we can have a base value and override it when we choose.

**Comment by dsheiko** [comment]
Claimed fixed in https://github.com/dsheiko/puppetry/releases/tag/v3.2.0-RC.1
