### ISSUE TITLE
ENHANCEMENT: add "Path to body" (JSON) in "mock request" command

### ISSUE THREAD

**Issue by TempleOfTemplar** [dsheiko/puppetry#54]
Please add the ability to use not only "Text body", but also the path to the JSON file. It makes this feature MUCH more useful, caule usually many tested pages makes similar requests.
![image](https://user-images.githubusercontent.com/8394644/70503595-8d90ec80-1b45-11ea-9493-263a3899db14.png)

**Comment by dsheiko** [comment]
A good one, accepted

**Comment by dsheiko** [comment]
Available since v3.1.0

**Comment by TempleOfTemplar** [comment]
THANK YOU SO SO SO MUCH! =)
