### ISSUE TITLE
Add an ability to test regression of elements by selector

### ISSUE THREAD

**Issue by DarkPreacher** [dsheiko/puppetry#55]
Rather than whole page. Or maybe it's possible already and I just can't find it?

**Comment by dsheiko** [comment]
Do you mean besides page.assertScreenshot to have TARGET.assertScreenshot ?

**Comment by DarkPreacher** [comment]
Yep, something like that.

**Comment by dsheiko** [comment]
Ok, accepted for the next releases https://github.com/dsheiko/puppetry/projects/5
Most likely 3.2.0 as 3.1.0 is ready to ship, just waiting for MacOS issue solution

**Comment by DarkPreacher** [comment]
Nice, thank you!

**Comment by dsheiko** [comment]
Claimed fixed in https://github.com/dsheiko/puppetry/releases/tag/v3.2.0-RC.1
