### ISSUE TITLE
How to run tests in safari, edge, etc?

### ISSUE THREAD

**Issue by zerkalica** [dsheiko/puppetry#56]
How to run puppetry scenarios for safari and edge browsers, etc. May be some workaround, selenium drivers?

**Comment by dsheiko** [comment]
The app is based on Puppeteer, which is Chromium API. You can still run exported tests in kind of Firefox with bundled https://github.com/puppeteer/puppeteer/tree/master/experimental/puppeteer-firefox. But nothing else.  I was thinking of writing a converter to Selenium. It would be a hell of work, what I cannot afford at the moment

**Comment by zerkalica** [comment]
Thanks.
Why converter? It's possible to create universal puppeteer to webdriver abstraction and do not change interfaces inside puppetry? 

May be this helps https://www.npmjs.com/package/webdriverjs-puppet?

**Comment by dsheiko** [comment]
Sorry, I've been on vacation. webdriverjs-puppet looks nice as an idea, but I assume implements only basic functionality. In Puppetry I was trying to use all the power of Puppeteer. If it's portable to Selenium webdriver even to some degree, it would take me ages to implement. No I cannot afford it. Too late.
