### ISSUE TITLE
Problem with recording when page is not secure with certificate. (broken HTTPS)

### ISSUE THREAD

**Issue by Zangethzu** [dsheiko/puppetry#59]
Hello, i tried record web with site which havent got certificate, it gives me problem cause i cant agree and continue in Puppetry. How can i resolve this problem? Thanks.
![Capture](https://user-images.githubusercontent.com/58010018/71765717-20d0fe00-2f09-11ea-8843-9db7aebbd2d8.JPG)

**Comment by dsheiko** [comment]
Thanks  for finding. It's now fixed on dev branch. To be deployed in a few days
