### ISSUE TITLE
Exporting project to my desktop deleted all files on my desktop

### ISSUE THREAD

**Issue by mortocks** [dsheiko/puppetry#6]
Exported project to /Users/{myusername}/Desktop

Export deleted all unrelated files from my desktop (VERY BAD!!!)

 and left the

- specs
- screenshots
- lib
- package.json
- README.md

files on the desktop.

I would expect it would only replace the files mentioned above or create a new folder with the name of the project and these files within them. Deleting files off the Desktop is a massive bug resulting in a lot of data loss for me.

**Comment by dsheiko** [comment]
Oh hell, that's embarrassing. I didn't think that through  Gonna  make it removing only the project files/dirs

**Comment by dsheiko** [comment]
Sorry, once again, and here the fix - v1.0.2
