### ISSUE TITLE
mockRequest: JSON file => absolute file path issue.

### ISSUE THREAD

**Issue by TempleOfTemplar** [dsheiko/puppetry#62]
For now - path to the JSON mock file is absolute. With this approach, several people will not be able to work on one project (because they have a different directory structure).
It seems to make sense to make this path relative. 

Also, when a project is exported to a .spec file, all mockRequest JSON files becomes inline. That makes editing or reading .spec files much more difficult. Example of generated code:
`await bs.mockRequest( "/api/openvpn", "GET", "200 OK", "application/json", "{INLINED JSON FILE HERE}");`
Maybe, it would be better to save .json files, for example, in a folder near .spec files?

**Comment by dsheiko** [comment]
Addressed in v3.2.0-RC.1
![screenshot-1582119851](https://user-images.githubusercontent.com/1393963/74839972-77ae5d80-5326-11ea-840b-ebe15af88ac0.png)

**Comment by dsheiko** [comment]
Claimed fixed in https://github.com/dsheiko/puppetry/releases/tag/v3.2.0-RC.1
