### ISSUE TITLE
Unable to create project

### ISSUE THREAD

**Issue by guidone** [dsheiko/puppetry#64]
On MacOs Catalina I'm not able to create a new project

<img width="1204" alt="Screen Shot 2020-03-02 at 10 50 14" src="https://user-images.githubusercontent.com/502519/75665009-bd96ea00-5c73-11ea-95d4-698ed3007c6a.png">

In Catalina the root is not writable. Where this "/web..." comes from? (I used to place projects here)

**Comment by dsheiko** [comment]
Hello, thanks for reporting. The directory, is the one you specify in the modal window when creating anew project. Just checked in Linux/Windows looks like no problems, gonna check possible in evening with my MacBook. But to me it looks like make sense to check ownership/permissions on the specified directory.
