### ISSUE TITLE
after at first time I run myTest project.

### ISSUE THREAD

**Issue by roughsoft** [dsheiko/puppetry#69]
which dir, I can run install command.
<img width="513" alt="Screen Shot 2020-05-02 at 12 36 56 PM" src="https://user-images.githubusercontent.com/459565/80855196-a96e6980-8c71-11ea-9f98-44c9c0c75bac.png">

**Comment by roughsoft** [comment]
my os is mac os 10.15

**Comment by dsheiko** [comment]
Please try to remove
`/Users/<USER_NAME>/Library/Logs/puppetry/.runtime-test`
and run the tests again. It looks like NPM  dependencies by some reason were not installed.

**Comment by roughsoft** [comment]
when i reinstall the npm packages,the puppetry crack when i download chrome

**Comment by roughsoft** [comment]
it is ok after I try again!Thank you!
