### ISSUE TITLE
Adding quote character in title causes tests to fail

### ISSUE THREAD

**Issue by mortocks** [dsheiko/puppetry#7]
Using quotes in the description/title of a test causes the test to fail. Assume it's a JSON parsing thing

*Examples*
Check price is prefixed with "each" word - fails
Check price is prefixed with each word - passes

*Screencapture*
https://www.dropbox.com/s/3k23k1x2139zka4/puppetry-titles.mov?dl=0

**Comment by dsheiko** [comment]
Oh, that's a really good one.  Fixed in https://github.com/dsheiko/puppetry/commit/29fbb5784bc2fbc49136764f8ef6b8df8c023762

**Comment by dsheiko** [comment]
deployed https://github.com/dsheiko/puppetry/releases/tag/v1.0.3
