### ISSUE TITLE
[FEATURE] Authentication

### ISSUE THREAD

**Issue by vsulak** [dsheiko/puppetry#70]
Please add page method `authenticate`. It would be useful for dev environments behind Basic Auth. Thank you

https://pptr.dev/#?product=Puppeteer&version=v3.0.2&show=api-pageauthenticatecredentials

**Comment by wideareashb** [comment]
You can do this by adding a step at the beginning of your test which looks like this:

<img width="1294" alt="image" src="https://user-images.githubusercontent.com/6398240/81008257-94006780-8e4a-11ea-8fa4-6cfb01c801ea.png">

Would prefer it to be an option in the test but does work

**Comment by vsulak** [comment]
Yes, I can override it. For now I use authentication in URL but original Puppeteer means would be more elegant.

**Comment by dsheiko** [comment]
Addressed in v.3.2.2, added example into Demo project
