### ISSUE TITLE
Can't seem to get SlowMo Working

### ISSUE THREAD

**Issue by BChip** [dsheiko/puppetry#71]
I noticed there is not a way to configure the SlowMo in the GUI. I also noticed if I change the SlowMo in the exported puppeteer.config.json, it doesn't seem to change anything. I tested on something ridiculous like 20,000 and it still executed and completed the tests at the same average speed.

Ex:
```
{
  "incognito": false,
  "puppeteer.connect": {
    "ignoreHTTPSErrors": true,
    "slowMo": 20000,
    "browserWSEndpoint": null
  },
  "puppeteer.launch": {
    "headless": true,
    "devtools": false,
    "ignoreHTTPSErrors": false,
    "args": [
      ""
    ]
  }
}
```

**Comment by dsheiko** [comment]
The issues is addressed in v.3.2.2
Export generates config file like:
```
{
  "incognito": true,
  "puppeteer.connect": {
    "ignoreHTTPSErrors": true,
    "browserWSEndpoint": null
  },
  "puppeteer.launch": {
    "devtools": false,
    "headless": true,
    "args": [],
    "slowMo": 30,
    "ignoreHTTPSErrors": false
  }
}
```

One can change `slowMo` property
