### ISSUE TITLE
Run Firefox fail

### ISSUE THREAD

**Issue by vfa-thuonglbl** [dsheiko/puppetry#72]
![Screen Shot 2020-06-02 at 6 41 27 PM](https://user-images.githubusercontent.com/44150324/83516204-dd52de00-a500-11ea-86e9-d854413c4a8e.png)
I config Firefox as above image. And click run, but below error happen.
![Screen Shot 2020-06-02 at 6 42 37 PM](https://user-images.githubusercontent.com/44150324/83516286-fc517000-a500-11ea-8802-ecdc4d809ff6.png)
May I config something wrong?

Mac OS Catalina 10.15.4
Firefox 76.0.1 (64-bit)
Execute path: /Applications/Firefox.app/Contents/MacOS/firefox-bin

**Comment by dsheiko** [comment]
It works with Nightly to me https://www.mozilla.org/en-US/firefox/channel/desktop/
/Applications/Firefox Nightly.app/Contents/MacOS/firefox-bin

Apparently Puppeteer support for Firefox is still buggy - for example https://github.com/puppeteer/puppeteer/issues/5806

**Comment by vfa-thuonglbl** [comment]
Thank you very much. I run on Firefox Nightly and can open browser.
But another problem happen.
![Screen Shot 2020-06-03 at 10 25 34 AM](https://user-images.githubusercontent.com/44150324/83592591-e4233480-a584-11ea-9c5c-23389c7d2031.png)
Error: Protocol error (Input.insertText): Input.insertText RemoteAgentError@chrome://remote/content/Error.jsm:25:5
https://github.com/puppeteer/puppeteer/issues/5392

My testcase is very simple, just input text and click button. And run OK on Chrome.
I really like the tool but with this bug I can't go on. Please help me solve it.

**Comment by dsheiko** [comment]
From my experience click on Firefox isn't working if the target is out of viewport, so please use --kiosk argument. Sincever 3.2.3  https://github.com/dsheiko/puppetry/releases/tag/v3.2.3 this argument has default value kiosk. Also I updated demo project. Now TodoMVC example is fully working in Firefox to me.

**Comment by vfa-thuonglbl** [comment]
![Screen Shot 2020-06-09 at 9 59 33 AM](https://user-images.githubusercontent.com/44150324/84101388-05c66500-aa38-11ea-87ff-5efe3abcdff6.png)
I downloaded newest version 3.2.3 and run on Firefox Nightly, same thingoccurs. 
I see --kiosk argument in this update but no effect for me.

Beside that, when I click Browser options -> Firefox -> Detect, it point to normal Firefox instead of Firefox Nightly. Maybe confuse user since support Firefox Nightly only.

**Comment by dsheiko** [comment]
Can you try TodoMVC example from Demo project. Dos it work to you?

**Comment by vfa-thuonglbl** [comment]
Yes, TodoMVC example work for me.

**Comment by dsheiko** [comment]
Well, you rather send me your test suite (json or export). I need to understand what is blocking

**Comment by vfa-thuonglbl** [comment]
`{
  "title": "HRM demo",
  "timeout": 50000,
  "snippets": false,
  "description": null,
  "savedAt": 1591671498,
  "loadedAt": 1591670108,
  "modified": false,
  "filename": "hrm--demo.json",
  "targets": {
    "ac2kaxtrhf4": {
      "editing": false,
      "id": "ac2kaxtrhf4",
      "key": "ac2kaxtrhf4",
      "target": "SIGN_IN_BTN",
      "selector": "/html[1]/body[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[4]/button[1]/div[2]",
      "disabled": false,
      "adding": false,
      "parentType": "",
      "ref": ""
    },
    "ac2kaxtrhi8": {
      "editing": false,
      "id": "ac2kaxtrhi8",
      "key": "ac2kaxtrhi8",
      "target": "FORGOT_PASS_BTN",
      "selector": "/html[1]/body[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[5]/a[1]/div[2]",
      "disabled": false,
      "adding": false,
      "parentType": "",
      "ref": ""
    },
    "ac2kaxtrhlb": {
      "editing": false,
      "id": "ac2kaxtrhlb",
      "key": "ac2kaxtrhlb",
      "target": "FORGET_PASS_TITLE",
      "selector": "/html[1]/body[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[2]",
      "disabled": false,
      "adding": false,
      "parentType": "",
      "ref": ""
    },
    "ac2kaxtrhov": {
      "editing": false,
      "id": "ac2kaxtrhov",
      "key": "ac2kaxtrhov",
      "target": "PASSWORD",
      "selector": "//*[@type=\"password\"]",
      "disabled": false,
      "adding": false,
      "parentType": "",
      "ref": ""
    },
    "ac2kaxtrhvf": {
      "editing": false,
      "id": "ac2kaxtrhvf",
      "key": "ac2kaxtrhvf",
      "target": "EMAIL",
      "selector": "//*[@type=\"email\"]",
      "disabled": false,
      "adding": false,
      "parentType": "",
      "ref": ""
    },
    "ac2kaxtri02": {
      "editing": false,
      "id": "ac2kaxtri02",
      "key": "ac2kaxtri02",
      "target": "FORGOT_PASS_TITLE",
      "selector": "/html[1]/body[1]/div[1]/div[1]/div[1]/main[1]",
      "disabled": false,
      "adding": false,
      "parentType": "",
      "ref": ""
    },
    "ac2kaxtri3i": {
      "editing": false,
      "id": "ac2kaxtri3i",
      "key": "ac2kaxtri3i",
      "target": "POPUP",
      "selector": "/html[1]/body[1]/div[2]/div[6]/div[1]/div[1]/div[1]",
      "disabled": false,
      "adding": false,
      "parentType": "",
      "ref": ""
    }
  },
  "groups": {
    "ac2kaxtrh6v": {
      "editing": false,
      "id": "ac2kaxtrh6v",
      "key": "ac2kaxtrh6v",
      "title": "Recorded session",
      "tests": {
        "ac2kaxtrh6w": {
          "editing": false,
          "id": "ac2kaxtrh6w",
          "key": "ac2kaxtrh6w",
          "title": "Recorded test case",
          "commands": {
            "ac2kaxtric4": {
              "editing": false,
              "id": "ac2kaxtric4",
              "key": "ac2kaxtric4",
              "target": "page",
              "method": "goto",
              "assert": {},
              "params": {
                "timeout": 30000,
                "url": "http://hrm.vitalify.asia/home",
                "waitUntil": "domcontentloaded"
              },
              "disabled": false,
              "failure": "",
              "variables": {},
              "expanded": false,
              "refName": "",
              "ref": "",
              "isRef": false,
              "groupId": "ac2kaxtrh6v",
              "testId": "ac2kaxtrh6w"
            },
            "ac2kaxtriei": {
              "editing": false,
              "id": "ac2kaxtriei",
              "key": "ac2kaxtriei",
              "target": "page",
              "method": "setViewport",
              "assert": {},
              "params": {
                "height": 678,
                "width": 1366
              },
              "disabled": false,
              "failure": "",
              "variables": {},
              "expanded": false,
              "refName": "",
              "ref": "",
              "isRef": false,
              "groupId": "ac2kaxtrh6v",
              "testId": "ac2kaxtrh6w",
              "waitForTarget": false
            },
            "ac2kaxtrigu": {
              "editing": false,
              "id": "ac2kaxtrigu",
              "key": "ac2kaxtrigu",
              "target": "EMAIL",
              "method": "type",
              "assert": {},
              "params": {
                "value": "abc@oi.doi"
              },
              "disabled": false,
              "failure": "",
              "variables": {},
              "expanded": false,
              "refName": "",
              "ref": "",
              "isRef": false,
              "groupId": "ac2kaxtrh6v",
              "testId": "ac2kaxtrh6w",
              "waitForTarget": true
            },
            "ac2kaxtriiy": {
              "editing": false,
              "id": "ac2kaxtriiy",
              "key": "ac2kaxtriiy",
              "target": "PASSWORD",
              "method": "type",
              "assert": {},
              "params": {
                "value": "ưer455"
              },
              "disabled": false,
              "failure": "",
              "variables": {},
              "expanded": false,
              "refName": "",
              "ref": "",
              "isRef": false,
              "groupId": "ac2kaxtrh6v",
              "testId": "ac2kaxtrh6w",
              "waitForTarget": true
            },
            "ac2kaxtril5": {
              "editing": false,
              "id": "ac2kaxtril5",
              "key": "ac2kaxtril5",
              "target": "SIGN_IN_BTN",
              "method": "click",
              "assert": {},
              "params": {
                "button": "left"
              },
              "disabled": false,
              "failure": "",
              "variables": {},
              "expanded": false,
              "refName": "",
              "ref": "",
              "isRef": false,
              "groupId": "ac2kaxtrh6v",
              "testId": "ac2kaxtrh6w",
              "waitForTarget": true
            },
            "ac2kaxu61n9": {
              "editing": false,
              "id": "ac2kaxu61n9",
              "key": "ac2kaxu61n9",
              "target": "POPUP",
              "method": "focus",
              "disabled": false,
              "failure": "",
              "variables": {},
              "expanded": false,
              "refName": "",
              "ref": "",
              "isRef": false,
              "groupId": "ac2kaxtrh6v",
              "testId": "ac2kaxtrh6w",
              "waitForTarget": true
            },
            "ac2kaxu6vef": {
              "editing": false,
              "id": "ac2kaxu6vef",
              "key": "ac2kaxu6vef",
              "target": "POPUP",
              "method": "assertVisible",
              "assert": {
                "assertion": "visible",
                "availability": "visible",
                "display": "any",
                "visibility": "any",
                "opacity": "any",
                "isIntersecting": "any"
              },
              "disabled": false,
              "failure": "",
              "variables": {},
              "expanded": false,
              "refName": "",
              "ref": "",
              "isRef": false,
              "groupId": "ac2kaxtrh6v",
              "testId": "ac2kaxtrh6w",
              "waitForTarget": false
            },
            "ac2kaxtrina": {
              "editing": false,
              "id": "ac2kaxtrina",
              "key": "ac2kaxtrina",
              "target": "FORGOT_PASS_BTN",
              "method": "click",
              "assert": {},
              "params": {
                "button": "left"
              },
              "disabled": false,
              "failure": "",
              "variables": {},
              "expanded": false,
              "refName": "",
              "ref": "",
              "isRef": false,
              "groupId": "ac2kaxtrh6v",
              "testId": "ac2kaxtrh6w",
              "waitForTarget": true
            },
            "ac2kaxtripn": {
              "editing": false,
              "id": "ac2kaxtripn",
              "key": "ac2kaxtripn",
              "target": "FORGOT_PASS_TITLE",
              "method": "click",
              "assert": {},
              "params": {
                "button": "left"
              },
              "disabled": false,
              "failure": "",
              "variables": {},
              "expanded": false,
              "refName": "",
              "ref": "",
              "isRef": false,
              "groupId": "ac2kaxtrh6v",
              "testId": "ac2kaxtrh6w",
              "waitForTarget": true
            },
            "ac2kaxu7h5k": {
              "editing": false,
              "id": "ac2kaxu7h5k",
              "key": "ac2kaxu7h5k",
              "target": "FORGET_PASS_TITLE",
              "method": "assertVisible",
              "assert": {
                "assertion": "visible",
                "availability": "visible",
                "display": "any",
                "visibility": "any",
                "opacity": "any",
                "isIntersecting": "any"
              },
              "disabled": false,
              "failure": "",
              "variables": {},
              "expanded": false,
              "refName": "",
              "ref": "",
              "isRef": false,
              "groupId": "ac2kaxtrh6v",
              "testId": "ac2kaxtrh6w",
              "waitForTarget": false
            }
          },
          "disabled": false,
          "expanded": false,
          "adding": false,
          "groupId": "ac2kaxtrh6v"
        }
      },
      "disabled": false,
      "expanded": false,
      "adding": false
    }
  },
  "puppetry": "3.2.3"
}`
this is my json file.

**Comment by dsheiko** [comment]
Thanks. It looks like there is an issue between Puppeteer and Firefox. The problem is here:
```
await ( await bs.getTarget( "PASSWORD" ) ).type( "ưer455" );
```
You have special UTF character and it by some reason crashes Firefox. If you change to any plain text - it works.
I have already reported https://github.com/puppeteer/puppeteer/issues/5991

**Comment by vfa-thuonglbl** [comment]
I replaced special char ư and it worked for Firefox.
Thank you very much.
`Beside that, when I click Browser options -> Firefox -> Detect, it point to normal Firefox instead of Firefox Nightly. Maybe confuse user since support Firefox Nightly only.`
How about this suggestion?

**Comment by dsheiko** [comment]
In the latest Puppetry version the Firefox support relies on the custom FF version embedded by Puppeteer
