### ISSUE TITLE
Update snap package

### ISSUE THREAD

**Issue by matopeter** [dsheiko/puppetry#73]
I like your app, so much easier to create tests now. Thank you very much for it ;D

Under Ubuntu it would be easier if we can install or update your last release from snap store. Please update the store version regularly, if it's possible.

**Comment by dsheiko** [comment]
Please visit https://snapcraft.io/puppetry

**Comment by matopeter** [comment]
Is the 3.1.1 the "latest stable" now? What about 3.2.2?

**Comment by dsheiko** [comment]
Latest stable already. I published today.

**Comment by matopeter** [comment]
I see now. The 3.1.1 was the latest about half hour ago. Thank you.
