### ISSUE TITLE
Template Variable in Assertion does not use variable value

### ISSUE THREAD

**Issue by apreston-jea** [dsheiko/puppetry#74]
I want to compare the value of a text input field against a local template variable but have not been successful in doing so. The documentation states that template expressions can be used in asserts. However, when we place the template expression into the Value field it sure looks like the resulting code tries to compare the value against the string “{{ VARIABLE_NAME }}” instead of the value of VARIABLE_NAME.
 
In the demo app I inserted an assertion into the Fill out the form snippet after the “Type {[ FIRST_NAME }}…” step.

![image](https://user-images.githubusercontent.com/66640324/84064877-3e066e80-a978-11ea-8335-b4fad426ec1c.png)

The generated code for the assertion is:
      expect( result ).toBeEqual( "{{ FIRST_NAME }}", "FIRSTNAME_INPUT.assertProperty" );

The parameter to toBeEqual() is the template variable name. It should be its value.

**Comment by dsheiko** [comment]
was fixed in 3.2.3
