### ISSUE TITLE
ReferenceError: path is not defined

### ISSUE THREAD

**Issue by eugenmihailescu** [dsheiko/puppetry#75]
By running a Puppetry (v3.2.3) test exported as Jest/Puppeteer project I get the following error: `ReferenceError: path is not defined`.

The error output looks like this:

```javascript
ReferenceError: path is not defined

      31 |               normalizedSuiteTitle = SUITE_NAME.replace( FILENAME_RE, "-" ),
      32 |               fileName = `${ id }.${ normalizedTitle }.png`;
    > 33 |               path = join( PATH_SCREENSHOTS, normalizedSuiteTitle,
         |                   ^
      34 |                 parentId !== null ? parentId + "." + fileName : fileName );
      35 |         shell.mkdir( "-p" , dirname( path ) );
      36 |         return { path, ...options };

      at Object.png (<some-path>/lib/helpers.js:33:19)
```
It looks like the `path` identifier is not defined within the `lib/helpers.js` file. By prefixing it simply with `const` the problem is solved.

Note: the command that I use to run the test is `npm run test` which will run a `react-scripts` wrapper that invoke the jest with a bunch of arguments. By running the `npm run test` within the exported Puppetry path, even by simply running `jest` in that directory, the problem does not occur. The difference probably is that one runs the JS in strict mode while the other don't.

Anyway, it is worth fixing that issue to make sure it works in both cases.

**Comment by dsheiko** [comment]
Thanks for reporting. The fix is https://github.com/dsheiko/puppetry/releases/tag/v3.2.4
