### ISSUE TITLE
Can't find puppetry-lock

### ISSUE THREAD

**Issue by mortocks** [dsheiko/puppetry#8]
Getting "Cannot export project" when trying to run tests

<img width="528" alt="screen shot 2018-12-09 at 1 24 15 pm" src="https://user-images.githubusercontent.com/314196/49693105-d4a47480-fbb5-11e8-9790-909e21d6da36.png">

Looking at the console logs, it looks like it's trying to reference a non-existent `puppetry-lock.json` file inside the `/.runtime-test/node_modules/` directory but this seems odd to me to reference a `*-lock.json` in the `node_modules` directory (but that might be the right implementation). 

I've tried deleting the `~/Library/Logs/puppetry` folder and relaunching the app. The `puppetry` folder is created again but the same error and console log happens. 

Version 1.0.2

Log output

```
[2018-12-09 13:20:02.517] [warn] Renderer process: RuntimeTest not ready, reason: could not lstat Error: ENOENT: no such file or directory, lstat '/Users/mortocks/Library/Logs/puppetry/.runtime-test/node_modules/puppetry-lock.json'
[2018-12-09 13:20:02.522] [warn] Renderer process: removeRuntimeTestPath
[2018-12-09 13:20:39.860] [warn] Renderer process: TestGenerator.parseCommand: Error: You have to provide all clip parameters
[2018-12-09 13:20:39.860] [warn] Renderer process: TestGenerator.generate: Error: You have to provide all clip parameters
[2018-12-09 13:20:39.860] [warn] Renderer process: io.exportProject(/Users/mortocks/Library/Logs/puppetry/.runtime-test/specs): Error: You have to provide all clip parameters
```

`.runtime-test` directory structure (`node_modules`) just contains the typical list of folders for each package. (Too long to show is a screenshot)

<img width="527" alt="screen shot 2018-12-09 at 1 29 14 pm" src="https://user-images.githubusercontent.com/314196/49693139-8d6ab380-fbb6-11e8-90ba-23d025392002.png">

**Comment by dsheiko** [comment]
Hello, thanks for the report. Apparently the problem is with tests,  not with the file creation. It simply caught the exception thrown during test spec parsing. Goo investigate tomorrow

**Comment by mortocks** [comment]
Site note: - I know I've left a bunch of bugs recently but it's because this app is amazing. Really want to help iron out some of these bugs so we can get it into our testing workflow. Nice work.

**Comment by dsheiko** [comment]
We are on the same page. I'm not myself really good in bug hunting, so any help is very appreciated.
As for the issue, you seem to have page.screenshot command(s) in your test, with clip position/size parameters. Could you please send my what is your options for screenshot? Especially for clip

**Comment by dsheiko** [comment]
Fix in https://github.com/dsheiko/puppetry/commit/29fbb5784bc2fbc49136764f8ef6b8df8c023762
It now explains that page.screen is missing clip options (one can got either with no clip options or all of them).  Besides I noted for myself to add param validation on form submit https://github.com/dsheiko/puppetry/wiki/Backlog
I'm planning full refactoring of form builder in 1.1 branch, then I address the validation

**Comment by dsheiko** [comment]
deployed https://github.com/dsheiko/puppetry/releases/tag/v1.0.3
