### ISSUE TITLE
Unable to run test suites

### ISSUE THREAD

**Issue by davidstocker** [dsheiko/puppetry#82]
I installed Puppetry from the MacOSX dmg, and also from source. When I attempt to run the demo suite (or any other), I encounter this error:

```
Determining test suites to run...[999D
RUNS ../../Library/Logs/puppetry/.runtime-test/specs/todomvc.spec.js
[1A FAIL ../../Library/Logs/puppetry/.runtime-test/specs/todomvc.spec.js
RUNS ../../Library/Logs/puppetry/.runtime-test/specs/todomvc.spec.js
[1A ● Test suite failed to run
Cannot find module 'puppeteer' from 'BrowserSession.js'
However, Jest was able to find:
'./BrowserSession.js'
You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].
```

**Comment by tbelousova** [comment]
The same here

**Comment by dsheiko** [comment]
Just tried myself on macOS Big Sur 11.2.3
- downloaded DMG and ran it from Finder by Ctrl-Click Open
- ran test from UI - like a charm
- exported tests, cd to the directory, npm install, npm test - all fine

When going from UI the project was created at `~/Library/Logs/puppetry/.runtime-test`

From your description I assume that on your env Puppetry fails to pull NPM dependencies programatically and likely have `~/Library/Logs/puppetry/.runtime-test/node_modules` empty. It may be related with security preferences. It may prompt for permission to create subfolder or something. I cannot reproduce so just guessing.
