### ISSUE TITLE
Hardcoded File Paths on Export

### ISSUE THREAD

**Issue by skipjack** [dsheiko/puppetry#98]
Relative paths (like the following one for uploading a file) are converted to absolute paths on export. This is problematic if you export on one machine and run the tests on another. Right now I'm working around this by running the following command within the exported directory...

```
cd specs && sed -i '' -E 's/".+assets\//"\.\.\/assets\//g' * && cd -
```

But obviously that's a bit hacky. I see a few options...

1. If there was a CLI to run puppetry exports, then everything could be run in the CI environment (e.g. GitHub Actions).
2. Add an export setting to configure how relative paths are coerced.

With option 1, the absolute paths _shouldn't_ be problematic given that they'd be based on the same machine's file structure. Option 2 would obviously yield much more flexibility though. Honestly it may be worth doing both but given that option 2 is likely the least involved option, it would make sense to start there. Adding option 2 would allow us to close this issue and maybe open a separate one to track the creation of a barebones `puppetry-cli` (which could probably be a separate repository package if desired).

**Comment by dsheiko** [comment]
Thank you for reporting, I'll deal with it soon

**Comment by dsheiko** [comment]
Well, just committed an update (to be released with the next version). The solution is - the path now supports template expressions. So you can use env expression to build the path like on the pic below:

![puppetry-upload-exp](https://user-images.githubusercontent.com/1393963/129049296-ac951402-f84c-4862-9435-5d64ee9987c8.PNG)

**Comment by skipjack** [comment]
Thanks for the follow up but I'm a little confused. Aren't the template variables hardcoded into the export? So if I set `MY_ASSETS_DIR` to `./assets` then exported will it not pull and hardcode the whole `{{ env("MY_ASSETS_DIR") }}/something.jpg` path into an absolute path?

**Comment by dsheiko** [comment]
On the contrary, the generated suite has code like this one:
```
     // Upload input[type=file]
      result = `${ process.env.PUPPETRY_ASSETS }/repeat-g1.png`;      
      await ( await bs.getTarget( "HEADER" ) ).uploadFile( result );
```
and path resolves according to what is in the env variable at the moment

**Comment by skipjack** [comment]
Ok... so we can change the environment on export to resolve it to a new base location for assets and nothing will be coerced to absolute paths 🎉

**Comment by skipjack** [comment]
> If there was a CLI to run puppetry exports, then everything could be run in the CI environment (e.g. GitHub Actions).

Should I create a separate issue for this one?

**Comment by dsheiko** [comment]
Yeah sure, but I'm not really understanding. Well, I use e.g. Gitlab CI to run the exported Jest project. The env variables I set in the configuration (`.gitlab-ci.yml`). Command line may look like:
```
./node_modules/.bin/jest --detectOpenHandles --forceExit --watchAll=false
```

**Comment by skipjack** [comment]
I'm talking about exporting the project programmatically, for example...

``` bash
puppetry export [suites or * for all]
```

Otherwise you need to manually export the project to something like `dist` and push that to GitHub/GitLab/etc. The proposed CLI would...

- Remove the need for the manual step if you're always exporting all suites.
- Address the security issues involved with including the exported project in a `git` repository, similar to my comments about `hidden` template variables in #86 they're also unprotected plain text in the exported project. This means that if you have to push that directory rather than programmatically generating it fresh before each run then you're exposing the credentials in your git history (something that's not easy to walk back).

Let me know if this makes sense or if I need to elaborate.
