### ISSUE TITLE
Unselected Test Suite Being Run

### ISSUE THREAD

**Issue by skipjack** [dsheiko/puppetry#99]
If you have multiple test suites in a project, and one happens to be the substring of another, then the running the substring one will cause both to be picked up. So in the following example (see the screenshot) if I run `invoices.json` then `changelog_header_invoices.json` will also be picked up.

![image](https://user-images.githubusercontent.com/8988697/127668707-ce80c67a-0b63-4373-9ee2-f61266a74580.png)

The steps above should make this straightforward to reproduce. We've seen the issue on two MacOS boxes running Big Sur 11.5.1 and Puppetry v3.2.5.

I have a feeling this is related to the fact that `jest` [accepts a regex pattern by default][1], not a specific filename. 

[1]: https://jestjs.io/docs/cli

**Comment by skipjack** [comment]
It looks like maybe [this module][1] is the one that would have to be updated?

[1]: https://github.com/dsheiko/puppetry/blob/973489904e8a6249a8732166e7ba76c1441d2760/app/main/test-runner.js

**Comment by skipjack** [comment]
I'm guessing that if we populate `targetFiles` with absolute or even relative file paths rather than names, it might address the issue.

**Comment by dsheiko** [comment]
Sorry for the delay. I'm back.
That's what you described a bit weird. The app doesn't rely on a pattern/glob. Instead it cleans up  temporary directory for Jest project and create a new one. It populates the `specs` subdirectory with test suite files depend on what is selected in checkbox group (like on your screenshot). So you have there any not intended suites I can think only that some where not removed during clean up. Checking now

**Comment by skipjack** [comment]
> The app doesn't rely on a pattern/glob.

My point was that `jest` [does][1]. So `jest invoices.spec.js` will actually run anything that ends in `invoices.spec.js` (e.g. `more-invoices.spec.js`) not just the exact match. Are you saying that Puppetry rebuilds a clean jest project every time you run using only the `.json` files selected so the `jest` pattern shouldn't matter?

[1]: https://jestjs.io/docs/cli

**Comment by dsheiko** [comment]
Oh, I got it now. While the export it's as I explained, but when you run the tests from the app it doesn't clean the directory - I'm on it.

**Comment by dsheiko** [comment]
just committed the fix, will be published with the next release.
